# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IMOnline' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 4.4'
	pod 'SwiftKeychainWrapper'
  # Pods for IMOnline

  target 'IMOnlineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IMOnlineUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  

end
